# Generated by Django 3.1.3 on 2020-11-21 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='_user_subscribers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
