# Generated by Django 3.1.3 on 2020-11-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201123_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateLink',
            fields=[
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('token', models.CharField(max_length=256)),
            ],
        ),
    ]
