# Generated by Django 3.1.3 on 2020-11-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activatelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivateLink',
        ),
    ]
